version: '3'

services:
  db:
    image: postgres:13-alpine
    env_file:
      - /backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:5050"
    depends_on:
      - db
    env_file:
      - /backend/.env
    

  backend:
    volumes:
      - /backend/app:/app
    env_file:
      - /backend/.env
    environment:
      - PORT=8000
    build:
      context: ./backend
      dockerfile: config_files/backend.dockerfile
    depends_on:
      - db


volumes:
  postgres_data: