version: '3'

services:
  db:
    image: postgres:13-alpine
    env_file:
      - /backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:5050"
    depends_on:
      - db
    env_file:
      - /backend/.env
    

  backend:
    ports:
      - 80:80
    volumes:
      - ./backend/app:/app
    env_file:
      - ./backend/.env
    build:
      context: ./backend/
      dockerfile: config_files/backend.dockerfile
    depends_on:
      - db
    command: /start-reload.sh


volumes:
  postgres_data: