"""Add column description table subject

Revision ID: 6916858de03d
Revises: 8295138216f6
Create Date: 2022-05-22 16:52:38.284274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6916858de03d'
down_revision = '8295138216f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject', 'description')
    # ### end Alembic commands ###
