"""Add table learned word

Revision ID: 73ab9ace5531
Revises: eb1e303f0814
Create Date: 2022-05-03 07:25:08.293752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ab9ace5531'
down_revision = 'eb1e303f0814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learnedword',
    sa.Column('word', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('mark_as_learned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['word'], ['word.id'], ),
    sa.PrimaryKeyConstraint('word', 'user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learnedword')
    # ### end Alembic commands ###
