"""Update column sample mean

Revision ID: 8295138216f6
Revises: b16144ee7dab
Create Date: 2022-05-22 15:46:09.730760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8295138216f6'
down_revision = 'b16144ee7dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('mean', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'mean')
    # ### end Alembic commands ###
