"""Update column table word

Revision ID: b16144ee7dab
Revises: 73ab9ace5531
Create Date: 2022-05-12 12:59:47.048604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16144ee7dab'
down_revision = '73ab9ace5531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('frequency', sa.String(), nullable=True))
    op.add_column('word', sa.Column('lemma', sa.String(), nullable=True))
    op.add_column('word', sa.Column('position', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'position')
    op.drop_column('word', 'lemma')
    op.drop_column('word', 'frequency')
    # ### end Alembic commands ###
